name: LSCore
version: '1.0-SNAPSHOT'
main: xyz.realplussmp.lSCore.LSCore
api-version: '1.21'
authors: [ mrrpmeowfurry ]
description: Core plugin for lifesteal
folia-supported: true
commands:
  revive:
    description: Revive a player
    usage: /revive <player>
    permission: lscore.revive